version: "3.9"

services:
    web:
        image: nginx:latest
        ports:
            - "8080:80"
        environment:
          - DEBIAN_FRONTEND=noninteractive
        volumes:
            - ./src:/var/www/html
            - ./default.conf:/etc/nginx/conf.d/default.conf
        links:
            - php-fpm
              #        command: /bin/bash -c 'chsh www-data -s /bin/bash && apt-get update && apt-get install -y sudo && usermod -aG sudo www-data && echo "www-data ALL=(ALL) NOPASSWD:/bin/grep" >> /etc/sudoers && chmod 400 /var/www/html/flag.txt  && nginx -g "daemon off;"'

    php-fpm:
        build: docker/php-fpm
        volumes:
            - ./src:/var/www/html
        command: /bin/bash -c 'apt-get update && apt-get install -y sudo && usermod -aG sudo www-data && echo "www-data ALL=(ALL) NOPASSWD:/bin/grep" >> /etc/sudoers && chmod 400 /var/www/html/flag.txt && php-fpm -F'
